---
apiVersion: v1
kind: Secret
metadata:
  name: abisheksmahesh2-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-deploy/abisheksmahesh2-backend-gitops
